sudo: required
services:
  - docker

before_install:
  - docker build -t saranonearth/demo -f Dockerfile.dev .

script:
  - docker run -e CI=true saranonearth/demo npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "ap-south-1"
  app: "demo"
  env: "Demo-env"
  bucket_name: "elasticbeanstalk-ap-south-1-116072917138"
  bucket_path: "demo"
  on:
    branch: master
